### ISSUE TITLE
User Profile-User should be able to upload a Photo

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#19] opened 2019-06-29 12:41 UTC
User Profile-User should be able to upload a Photo

**Comment by FayazMaacolony** [comment] 2019-07-06 09:01
![User Profile-User should be able to upload a Photo](https://user-images.githubusercontent.com/51132032/60754160-b6431200-9ffa-11e9-907b-b705078617dc.jpg)

**Comment by Rajeswari06** [comment] 2019-10-11 02:34
duplicate of 25

**Comment by RamanaKiran** [comment] 2019-10-20 10:01
Its duplicate issue

**Closed as completed by RamanaKiran** 2019-10-20 10:01 UTC
Labels: bug, duplicate, API Required
