### ISSUE TITLE
Expenses: Unable to download recently uploaded attachment

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#30] opened 2019-07-21 11:34 UTC
Expenses: Unable to download recently uploaded attachment

**Comment by Rajeswari06** [comment] 2019-10-06 11:15
due to lack of attachment information after attached

**Comment by Rajeswari06** [comment] 2019-10-11 02:31
Duplicate of 73 and 31.

**Comment by RamanaKiran** [comment] 2019-10-20 10:02
iys duplicate

**Closed as completed by RamanaKiran** 2019-10-20 10:02 UTC
Labels: duplicate, API Required
