### ISSUE TITLE
MaaColony Mobile App-User Profile-Updated changes are not reflecting in User Profile

### ISSUE THREAD

**Issue by FayazMaacolony** [ijazakram/MaaColony#5] opened 2019-06-16 12:34 UTC
Updated changes are not reflecting in User Profile

**Comment by FayazMaacolony** [comment] 2019-06-29 09:44
Unable to save Profile, even after selecting Member type hence closing the issue.

**Comment by ijazakram** [comment] 2019-07-08 03:10
@Rajeswari06 Including the above issues, we need to save country code dynamically & display country code in the phone section as dynamically. Please add this one also.

**Comment by RamanaKiran** [comment] 2019-10-02 03:30
For Country Code list make use of the below API -

https://test.maacolony.com/api/GCMemberApi/GetCodeList/?codeListID=27

**Comment by Rajeswari06** [comment] 2019-10-11 02:35
Duplicate of 79

**Closed as completed** 2019-10-20 10:42 UTC
Labels: bug, duplicate
